name: trackfood
version: 1.0.0+1
description: TrackFood - Intelligente Ernährungs-Tracking-App
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.0
  uuid: ^4.4.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.0
  barcode_scan2: ^4.5.1
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.0
  # riverpod: ^2.5.1
  # flutter_bloc: ^8.1.5
  # flutter_quill: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/logo1.webp
